"""empty message

Revision ID: a09e343f1a1e
Revises: 6375c75e6ba8
Create Date: 2020-12-08 18:02:09.098460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09e343f1a1e'
down_revision = '6375c75e6ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('isdelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isdelete')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
