"""first

Revision ID: 5cf23569b12b
Revises: 
Create Date: 2021-06-23 16:12:52.771052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cf23569b12b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user_1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uname', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('t_emp')
    op.drop_table('t_deptno')
    op.drop_table('t_temp_tab')
    op.drop_table('t_id_card')
    op.drop_table('t_course')
    op.drop_table('t_student')
    op.drop_table('t_person')
    op.drop_table('t_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uname', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.create_table('t_person',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.create_table('t_student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.create_table('t_course',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('c_name', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.create_table('t_id_card',
    sa.Column('card_number', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('p_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['t_person.id'], name='t_id_card_ibfk_1'),
    sa.PrimaryKeyConstraint('card_number'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.create_table('t_temp_tab',
    sa.Column('s_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('c_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['t_course.id'], name='t_temp_tab_ibfk_2'),
    sa.ForeignKeyConstraint(['s_id'], ['t_student.id'], name='t_temp_tab_ibfk_1'),
    sa.PrimaryKeyConstraint('s_id', 'c_id'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.create_table('t_deptno',
    sa.Column('dept_no', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('d_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('dept_no'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.create_table('t_emp',
    sa.Column('emp_no', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('e_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('job', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hire_data', sa.DATE(), nullable=True),
    sa.Column('sal', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('dept_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_no'], ['t_deptno.dept_no'], name='t_emp_ibfk_1'),
    sa.PrimaryKeyConstraint('emp_no'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_user_1')
    # ### end Alembic commands ###
