"""empty message

Revision ID: 090ff03ec1cb
Revises: 22ebc596e7b1
Create Date: 2020-12-16 19:08:33.465457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090ff03ec1cb'
down_revision = '22ebc596e7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('desc', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'desc')
    # ### end Alembic commands ###
