"""empty message

Revision ID: 327310a74fee
Revises: 987fbd46ea0d
Create Date: 2020-10-04 18:52:26.784246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327310a74fee'
down_revision = '987fbd46ea0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
